name: ai_frontend
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
# /home/eugene/snap/flutter/common/flutter/packages/flutter_tools/gradle to change minSDK to 19
  device_info_plus: ^9.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  # in_app_review: ^2.0.6
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
      - images/